# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)




# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' + user.email

user = User.new
user.email = 'test@example.com'
user.password = '12345678'
user.password_confirmation = '12345678'
user.save!


Word.create("pos" => "noun","content" => "time")
Word.create("pos" => "noun","content" => "person")
Word.create("pos" => "noun","content" => "year")
Word.create("pos" => "noun","content" => "way")
Word.create("pos" => "noun","content" => "day")
Word.create("pos" => "noun","content" => "thing")
Word.create("pos" => "noun","content" => "man")
Word.create("pos" => "noun","content" => "world")
Word.create("pos" => "noun","content" => "life")
Word.create("pos" => "noun","content" => "hand")
Word.create("pos" => "noun","content" => "part")
Word.create("pos" => "noun","content" => "child")
Word.create("pos" => "noun","content" => "eye")
Word.create("pos" => "noun","content" => "woman")
Word.create("pos" => "noun","content" => "place")
Word.create("pos" => "noun","content" => "work")
Word.create("pos" => "noun","content" => "week")
Word.create("pos" => "noun","content" => "case")
Word.create("pos" => "noun","content" => "point")
Word.create("pos" => "noun","content" => "government")
Word.create("pos" => "noun","content" => "company")
Word.create("pos" => "noun","content" => "number")
Word.create("pos" => "noun","content" => "group")
Word.create("pos" => "noun","content" => "problem")
Word.create("pos" => "noun","content" => "fact")

Word.create("pos" => "verb","content" => "be")
Word.create("pos" => "verb","content" => "have")
Word.create("pos" => "verb","content" => "do")
Word.create("pos" => "verb","content" => "say")
Word.create("pos" => "verb","content" => "get")
Word.create("pos" => "verb","content" => "make")
Word.create("pos" => "verb","content" => "go")
Word.create("pos" => "verb","content" => "know")
Word.create("pos" => "verb","content" => "take")
Word.create("pos" => "verb","content" => "see")
Word.create("pos" => "verb","content" => "come")
Word.create("pos" => "verb","content" => "think")
Word.create("pos" => "verb","content" => "look")
Word.create("pos" => "verb","content" => "want")
Word.create("pos" => "verb","content" => "give")
Word.create("pos" => "verb","content" => "use")
Word.create("pos" => "verb","content" => "find")
Word.create("pos" => "verb","content" => "tell")
Word.create("pos" => "verb","content" => "ask")
Word.create("pos" => "verb","content" => "work")
Word.create("pos" => "verb","content" => "seem")
Word.create("pos" => "verb","content" => "feel")
Word.create("pos" => "verb","content" => "try")
Word.create("pos" => "verb","content" => "leave")
Word.create("pos" => "verb","content" => "call")

Word.create("pos" => "others","content" => "the")
Word.create("pos" => "others","content" => "and")
Word.create("pos" => "others","content" => "a")
Word.create("pos" => "others","content" => "that")
Word.create("pos" => "others","content" => "I")
Word.create("pos" => "others","content" => "it")
Word.create("pos" => "others","content" => "not")
Word.create("pos" => "others","content" => "he")
Word.create("pos" => "others","content" => "as")
Word.create("pos" => "others","content" => "you")
Word.create("pos" => "others","content" => "this")
Word.create("pos" => "others","content" => "but")
Word.create("pos" => "others","content" => "his")
Word.create("pos" => "others","content" => "they")
Word.create("pos" => "others","content" => "her")
Word.create("pos" => "others","content" => "she")
Word.create("pos" => "others","content" => "or")
Word.create("pos" => "others","content" => "an")
Word.create("pos" => "others","content" => "will")
Word.create("pos" => "others","content" => "my")
Word.create("pos" => "others","content" => "one")
Word.create("pos" => "others","content" => "all")
Word.create("pos" => "others","content" => "would")
Word.create("pos" => "others","content" => "there")
Word.create("pos" => "others","content" => "their")


Word.create("pos" => "adjective","content" => "good")
Word.create("pos" => "adjective","content" => "new")
Word.create("pos" => "adjective","content" => "first")
Word.create("pos" => "adjective","content" => "last")
Word.create("pos" => "adjective","content" => "long")
Word.create("pos" => "adjective","content" => "great")
Word.create("pos" => "adjective","content" => "little")
Word.create("pos" => "adjective","content" => "own")
Word.create("pos" => "adjective","content" => "other")
Word.create("pos" => "adjective","content" => "old")
Word.create("pos" => "adjective","content" => "right")
Word.create("pos" => "adjective","content" => "big")
Word.create("pos" => "adjective","content" => "high")
Word.create("pos" => "adjective","content" => "different")
Word.create("pos" => "adjective","content" => "small")
Word.create("pos" => "adjective","content" => "large")
Word.create("pos" => "adjective","content" => "next")
Word.create("pos" => "adjective","content" => "early")
Word.create("pos" => "adjective","content" => "young")
Word.create("pos" => "adjective","content" => "important")
Word.create("pos" => "adjective","content" => "few")
Word.create("pos" => "adjective","content" => "public")
Word.create("pos" => "adjective","content" => "bad")
Word.create("pos" => "adjective","content" => "same")
Word.create("pos" => "adjective","content" => "able")


Word.create("pos" => "prepositions","content" => "to")
Word.create("pos" => "prepositions","content" => "of")
Word.create("pos" => "prepositions","content" => "in")
Word.create("pos" => "prepositions","content" => "for")
Word.create("pos" => "prepositions","content" => "on")
Word.create("pos" => "prepositions","content" => "with")
Word.create("pos" => "prepositions","content" => "at")
Word.create("pos" => "prepositions","content" => "by")
Word.create("pos" => "prepositions","content" => "from")
Word.create("pos" => "prepositions","content" => "up")
Word.create("pos" => "prepositions","content" => "about")
Word.create("pos" => "prepositions","content" => "into")
Word.create("pos" => "prepositions","content" => "over")
Word.create("pos" => "prepositions","content" => "after")
Word.create("pos" => "prepositions","content" => "beneath")
Word.create("pos" => "prepositions","content" => "under")
Word.create("pos" => "prepositions","content" => "above")


Word.create("pos" => "suffix","content" => "s")
Word.create("pos" => "suffix","content" => "es")
Word.create("pos" => "suffix","content" => "ed")
Word.create("pos" => "suffix","content" => "ing")
Word.create("pos" => "suffix","content" => "ly")
Word.create("pos" => "suffix","content" => "er")
Word.create("pos" => "suffix","content" => "or")
Word.create("pos" => "suffix","content" => "y")
Word.create("pos" => "suffix","content" => "ness")
Word.create("pos" => "suffix","content" => "al")
Word.create("pos" => "suffix","content" => "ion")
Word.create("pos" => "suffix","content" => "ity")
Word.create("pos" => "suffix","content" => "ment")
Word.create("pos" => "suffix","content" => "ty")
Word.create("pos" => "suffix","content" => "er")
Word.create("pos" => "suffix","content" => "ive")
Word.create("pos" => "suffix","content" => "ful")
Word.create("pos" => "suffix","content" => "less")
Word.create("pos" => "suffix","content" => "est")
Word.create("pos" => "suffix","content" => "ative")
Word.create("pos" => "suffix","content" => "tive")
